application: cloudtodolist
version: 1
runtime: python
api_version: 1


handlers:
- url: /todolist/entries
  script: todolist_server.py

- url: /todolist/entries/\d+
  script: todolist_server.py

- url: /todolist/tasks/.*
  script: todolist_server.py
  login: admin

- url: /todolist/update_channel
  script: todolist_server.py

- url: /_ah/channel/connected/
  script: todolist_server.py

- url: /_ah/channel/disconnected/
  script: todolist_server.py

- url: /todolist
  static_dir: todolist/static/

- url: /
  script: todolist_server.py
  login: required

- url: /favicon.ico
  static_files: todolist/static/favicon.ico
  upload: todolist/static/favicon.ico


inbound_services:
- channel_presence


