
CREATE TABLE IF NOT EXISTS entries (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(32) NOT NULL DEFAULT '',
  notes VARCHAR(1024) NOT NULL DEFAULT '',
  complete BOOLEAN NOT NULL DEFAULT FALSE,
  created DOUBLE NOT NULL,
  modified DOUBLE NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE
) ENGINE=INNODB;

DROP VIEW IF EXISTS current_entries;
CREATE VIEW current_entries
  AS SELECT * FROM ENTRIES WHERE deleted = 0;
