DROP DATABASE IF EXISTS todolist;
CREATE DATABASE todolist;
USE todolist;

CREATE TABLE entries (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(32),
  notes VARCHAR(1024),
  complete BOOLEAN NOT NULL DEFAULT FALSE
) ENGINE=INNODB;







